In [ ]:
#q1(a)
import numpy as np
arr_1d=np.array([1,2,3,4,5])
for i in range(len(arr_1d)):
  arr_1d[i]=arr_1d[i]+2
print(arr_1d)




[3 4 5 6 7]


In [ ]:
#q1(b)
import numpy as np
arr_1d=np.array([1,2,3,4,5])
for i in range(len(arr_1d)):
  arr_1d[i]=arr_1d[i]*3
print(arr_1d)

[ 3  6  9 12 15]


In [ ]:
#q1(c)
import numpy as np
arr_1d=np.array([1,2,3,4,5])
for i in range(len(arr_1d)):
  arr_1d[i]=arr_1d[i]/2
print(arr_1d)

[0 1 1 2 2]


In [ ]:
#q2(a)
arr = np.array([1, 2, 3, 6, 4, 5])
r_arr=np.flip(arr)
print(r_arr)

[5 4 6 3 2 1]


In [ ]:
#q2(b)
x = np.array([1,2,3,4,5,1,2,1,1,1])
count={}
for i in range(len(x)):
  if



In [ ]:
#q3
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [ ]:
#q4
import numpy as np
your_name = np.linspace(10, 100, 25)
your_name.ndim
your_name.shape
your_name.size
your_name.dtype
your_name.nbytes
your_name.reshape(25,1)
#T attribute doesn’t change 1D arrays because NumPy considers them as neither row nor column vectors.

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

In [ ]:
#q5
import numpy as np
ucs420_yourname = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

mean_value = np.mean(ucs420_yourname)
median_value = np.median(ucs420_yourname)
max_value = np.max(ucs420_yourname)
min_value = np.min(ucs420_yourname)
unique_elements = np.unique(ucs420_yourname)
print("Original 2D Array:\n", ucs420_yourname)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)

reshaped_ucs420_yourname = ucs420_yourname.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_yourname)

resized_ucs420_yourname =np.resize(ucs420_yourname, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_yourname)

Original 2D Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
